---
- name: Install docker
  include_tasks: docker.yml
  vars:
    ansible_become: yes

- name: Create sysctl settings file for bridge settings
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
    mode: '644'
  register: sysctl_k8s_conf
  become: yes

- name: Load new sysctl settings
  command: sysctl --system
  when: sysctl_k8s_conf is changed
  become: yes

- name: Remove swap volumes from /etc/fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    # This should match all lines with an fstype of "swap"
    regexp: '^[^\s]+\s+[^\s]+\s+swap\s+'
  register: remove_swap_volumes
  become: yes

- name: Disable swap
  command: swapoff --all
  when: remove_swap_volumes is changed
  become: yes

- name: Create rke group
  group:
    name: rke
    system: yes
  become: yes

- name: Add rke user
  user:
    name: rke
    comment: "Rancher RKE"
    system: yes
    group: rke
    groups:
      - docker
  become: yes

- name: Setup ssh authorized key for rke
  authorized_key:
    user: rke
    exclusive: yes
    key: "{{ lookup('file', '/tmp/rke/ssh_id_rsa.pub') }}"
  become: yes
