---
- name: Ensure config directory exists
  file:
    path: "{{ rke_config_dir }}"
    state: directory
    mode: '700'

- name: Generate ssh-key to use by rke
  community.crypto.openssh_keypair:
    path: "{{ rke_config_dir }}/ssh_id_rsa"
  when: rke_ssh_key_private | length == 0 or rke_ssh_key_public | length == 0

- name: Save provided ssh private key
  ansible.builtin.copy:
    content: "{{ rke_ssh_key_private }}"
    dest: "{{ rke_config_dir }}/ssh_id_rsa"
  when: rke_ssh_key_private | length > 0 and rke_ssh_key_public | length > 0

- name: Save provided ssh public key
  ansible.builtin.copy:
    content: "{{ rke_ssh_key_public }}"
    dest: "{{ rke_config_dir }}/ssh_id_rsa.pub"
  when: rke_ssh_key_private | length > 0 and rke_ssh_key_public | length > 0

- name: Get public ssh-key to use by rke
  ansible.builtin.fetch:
    src: "{{ rke_config_dir }}/ssh_id_rsa.pub"
    dest: /tmp/rke/
    flat: true
