---
- name: Fail if some hosts has failed
  fail:
    msg: Some of the hosts has failed
  when: ansible_play_hosts_all| difference(ansible_play_batch) | length > 0

- name: Test ssh accesses
  ansible.builtin.shell:
    cmd: |
      ssh -o "StrictHostKeyChecking=no" -o "BatchMode=yes" -i {{ rke_config_dir }}/ssh_id_rsa rke@{{ hostvars[item]['ansible_' + host_interface].ipv4.address }} true
    chdir: "{{ rke_config_dir }}"
  when: hostvars[item].rke_node_roles | length > 0
  changed_when: false
  with_items: "{{ ansible_play_hosts }}"

- name: Get current installet version of RKE binary
  shell: "rke -v | awk '{ print $3 }' || true"
  register: rke_binary_version
  changed_when: false

- name: Download RKE binary
  get_url:
    url: "{{ rke_binary_url }}"
    checksum: "{{ rke_binary_checksum }}"
    dest: /usr/local/bin/rke
    mode: "+rx"
    force: "{{ rke_binary_version.stdout != rke_release }}"
  register: rke_binary
  become: true

- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ rke_kubernetes_version.split('-', 1)[0] }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    force: true
    mode: "+rx"
  become: true

- name: Ensure config directory exists
  file:
    path: "{{ rke_config_dir }}"
    state: directory
    mode: '700'

- include: "{{ rke_before_up_hook | default('empty.yml') }}"
  register: include_rke_before_up_hook

- name: Create/update RKE config file
  template:
    src: rke_cluster.j2
    dest: "{{ rke_config_dir }}/cluster.yml"
    mode: '600'
  register: rke_cluster_config

- name: Check RUNNING file
  stat:
    path: "{{ rke_config_dir }}/RUNNING"
  register: running

- name: Run RKE installer
  shell: |
    set -eo pipefail
    touch RUNNING
    rke up | tee rke-up_$(date +%Y-%m-%d_%H%M%S).log
    rm -f RUNNING
  args:
    chdir: "{{ rke_config_dir }}"
    executable: /usr/bin/bash
  when: rke_binary is changed or rke_cluster_config is changed or rke_force_configure or running.stat.exists or include_rke_before_up_hook is changed

- name: Ensure $HOME/.kube exists
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '700'

- name: Copy kubeconfig to default location
  copy:
    remote_src: true
    src: "{{ rke_config_dir }}/kube_config_cluster.yml"
    dest: "{{ ansible_env.HOME }}/.kube/config"
    mode: '600'

- name: Verify kubectl working
  shell: kubectl get all
  changed_when: false
