---
- name: Converge
  hosts: all
  tasks:
    - name: "Include rke"
      include_role:
        name: "rke"
  vars:
    cluster_name: "molecule-test"
    cluster_interface: eth1
    rke_release: v1.2.6
    rke_binary_checksum: sha256:6d4a44931cf2fddbac742b24a4172ecf41ab199eee047cb8fa598e15e45fff8c
    kubernetes_supported_versions:
      "1.19": v1.19.8-rancher1-1
    docker_version: "latest"
